In [ ]:
# downloading the two final_byte_bigram form google drive
! gdown --id 1IVYm9bJSnQqlUOoBV9fJDUxCvAhgswTK

/usr/local/lib/python3.7/dist-packages/gdown/cli.py:131: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  category=FutureWarning,
Downloading...
From: https://drive.google.com/uc?id=1IVYm9bJSnQqlUOoBV9fJDUxCvAhgswTK
To: /content/final_byte_bigram.npz
100% 672M/672M [00:10<00:00, 65.7MB/s]

In [ ]:
! gdown --id 1yF0hxINMMLbrrl32ADOErPy5JNDsyrKJ

/usr/local/lib/python3.7/dist-packages/gdown/cli.py:131: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  category=FutureWarning,
Downloading...
From: https://drive.google.com/uc?id=1yF0hxINMMLbrrl32ADOErPy5JNDsyrKJ
To: /content/final_byte_bigram2.npz
100% 431M/431M [00:07<00:00, 61.1MB/s]

In [ ]:
# we have two files final_byte_bigram and final_byte_bigram2 
import scipy.sparse
final1 = scipy.sparse.load_npz('/content/final_byte_bigram2.npz')

In [ ]:
final2 = scipy.sparse.load_npz('/content/final_byte_bigram.npz')

In [ ]:
# final stacking of all the byte files
import scipy.sparse
f = scipy.sparse.vstack((final2,final1))

In [ ]:
del final1 , final2

In [ ]:
train_labels = pd.read_csv("trainLabels.csv")

In [ ]:
# perfroming feature selection of byte bigram file
# Here out of 66k feature we are selcting top 2000 
import pandas as pd
from sklearn.feature_selection import SelectKBest , chi2 , f_regression
select_Kbest_object = SelectKBest(score_func = chi2 , k= 2000)
most_imp_fea = select_Kbest_object.fit(f,train_labels['Class'])

imp_byte_bigram_feature_scores = pd.DataFrame(most_imp_fea.scores_)

# Reference : https://www.analyticsvidhya.com/blog/2020/10/feature-selection-techniques-in-machine-learning/

In [ ]:
top_2000_byte_bigram = select_Kbest_object.fit_transform(f,train_labels['Class'])

In [ ]:
top_2000_byte_bigram

<10868x2000 sparse matrix of type '<class 'numpy.float64'>'
	with 15449763 stored elements in Compressed Sparse Column format>

In [ ]:
#Normlaizing the data
from sklearn.preprocessing import normalize
top_2000_byte_bigram = normalize(top_2000_byte_bigram,axis = 0)

In [ ]:
top_2000_byte_bigram.shape

(10868, 2000)

In [ ]:
# Converting into pandas datagrame
data = pd.DataFrame(top_2000_byte_bigram.toarray())

In [ ]:
data.to_csv("byte_bigram.csv")

In [ ]:
n = pd.read_csv("byte_bigram.csv")

In [ ]:
n

,Unnamed: 0,0,1,2,3,4,5,6,7,8,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
0,0,0.002984,0.000082,0.000008,0.000135,0.000093,0.000064,0.000077,0.000026,0.000042,...,0.000000,0.000000,0.000013,0.000020,0.000000,0.000000,0.000000,0.000031,0.000000,0.005491
1,1,0.002367,0.000064,0.000023,0.000052,0.000109,0.000258,0.000063,0.000078,0.000030,...,0.000045,0.000026,0.000040,0.000041,0.000024,0.000013,0.000023,0.000062,0.000015,0.000693
2,2,0.000483,0.000155,0.000085,0.000045,0.000311,0.000386,0.000105,0.000168,0.000042,...,0.000359,0.000104,0.000212,0.000225,0.000076,0.000173,0.000056,0.000342,0.000037,0.000062
3,3,0.028391,0.000430,0.000054,0.000329,0.000450,0.000901,0.000525,0.000607,0.000103,...,0.000000,0.000035,0.000027,0.000123,0.000052,0.000027,0.000000,0.000124,0.000037,0.005433
4,4,0.005011,0.000155,0.000062,0.000264,0.000078,0.000558,0.000175,0.000116,0.000272,...,0.000000,0.000000,0.000013,0.000041,0.003454,0.000000,0.000014,0.000000,0.002064,0.199643
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10863,10863,0.001226,0.000137,0.000202,0.000110,0.000373,0.000386,0.000112,0.000155,0.000079,...,0.000269,0.000095,0.000119,0.000307,0.000062,0.000213,0.000075,0.000405,0.000037,0.000175
10864,10864,0.003809,0.000027,0.000209,0.000084,0.000031,0.000043,0.000049,0.000013,0.000012,...,0.000045,0.000009,0.000027,0.000000,0.000885,0.000013,0.000000,0.000000,0.000521,0.000755
10865,10865,0.001087,0.000201,0.000140,0.000129,0.000435,0.000472,0.000126,0.000233,0.000066,...,0.000336,0.000095,0.000239,0.000328,0.000038,0.000173,0.000051,0.000436,0.000026,0.000114
10866,10866,0.004771,0.000119,0.000008,0.000174,0.000140,0.000279,0.002241,0.000052,0.000048,...,0.000000,0.002090,0.000013,0.000020,0.339224,0.000000,0.000005,0.000000,0.000007,0.010462
10867,10867,0.021719,0.000165,0.000047,0.000077,0.000047,0.000579,0.000063,0.000090,0.000048,...,0.000045,0.000043,0.000040,0.000041,0.000080,0.000093,0.000019,0.000093,0.000295,0.002017